from __future__ import annotations

import json
from dataclasses import asdict, dataclass, field
from datetime import datetime
from hashlib import sha256
from typing import Any, Dict, List, Optional

from .llm import _repair_mojibake


def _clean_list(values: Optional[List[str]]) -> List[str]:
    cleaned: List[str] = []
    for value in values or []:
        repaired = _repair_mojibake(value)
        if isinstance(repaired, (dict, list)):
            text = json.dumps(repaired, ensure_ascii=False)
        else:
            text = str(repaired)
        if text.strip():
            cleaned.append(text.strip())
    return cleaned


@dataclass
class AgentRole:
    """Role definition for one strategy-research agent."""

    name: str
    mission: str
    perspective: str
    model_tier: str = "quick"
    required_outputs: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class RoleReport:
    """Structured output produced by one role."""

    role: str
    thesis: str
    evidence: List[str] = field(default_factory=list)
    proposals: List[str] = field(default_factory=list)
    risks: List[str] = field(default_factory=list)
    verdict: str = "continue"
    confidence: float = 0.5
    next_actions: List[str] = field(default_factory=list)
    prompt_name: Optional[str] = None
    upstream_roles: List[str] = field(default_factory=list)
    required_outputs: List[str] = field(default_factory=list)
    schema_warnings: List[str] = field(default_factory=list)
    raw_response: Optional[str] = None

    @classmethod
    def from_dict(cls, role: str, payload: Dict[str, Any], raw_response: str | None = None) -> "RoleReport":
        return cls(
            role=str(payload.get("role") or role),
            thesis=str(payload.get("thesis") or payload.get("analysis") or ""),
            evidence=_clean_list(payload.get("evidence")),
            proposals=_clean_list(payload.get("proposals")),
            risks=_clean_list(payload.get("risks") or payload.get("risk_warnings")),
            verdict=str(payload.get("verdict") or "continue"),
            confidence=float(payload.get("confidence") or 0.5),
            next_actions=_clean_list(payload.get("next_actions")),
            prompt_name=str(payload.get("prompt_name") or "") or None,
            upstream_roles=_clean_list(payload.get("upstream_roles")),
            required_outputs=_clean_list(payload.get("required_outputs")),
            schema_warnings=_clean_list(payload.get("schema_warnings")),
            raw_response=raw_response,
        )

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class ChairDecision:
    """Virtual meeting chair decision for adaptive role participation."""

    turn_index: int
    action: str = "call_role"
    next_role: str = ""
    next_roles: List[str] = field(default_factory=list)
    rationale: str = ""
    focus: str = ""
    decision: str = "continue"
    final_summary: str = ""
    confidence: float = 0.5
    coverage: Dict[str, bool] = field(default_factory=dict)
    missing_requirements: List[str] = field(default_factory=list)
    blocked_reason: str = ""

    @classmethod
    def from_dict(cls, turn_index: int, payload: Dict[str, Any]) -> "ChairDecision":
        next_roles = _clean_list(payload.get("next_roles"))
        if not next_roles:
            next_role = str(payload.get("next_role") or payload.get("role") or "")
            next_roles = [next_role] if next_role else []
        return cls(
            turn_index=turn_index,
            action=str(payload.get("action") or "call_role"),
            next_role=next_roles[0] if next_roles else "",
            next_roles=next_roles,
            rationale=str(payload.get("rationale") or payload.get("why") or ""),
            focus=str(payload.get("focus") or payload.get("question") or ""),
            decision=str(payload.get("decision") or "continue"),
            final_summary=str(payload.get("final_summary") or payload.get("summary") or ""),
            confidence=float(payload.get("confidence") or 0.5),
            coverage=dict(payload.get("coverage") or {}),
            missing_requirements=_clean_list(payload.get("missing_requirements")),
            blocked_reason=str(payload.get("blocked_reason") or ""),
        )

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class ExperimentArm:
    """One controlled experiment candidate generated by the agent team."""

    arm_id: str
    hypothesis: str
    change_type: str
    owner_role: str
    config_path: Optional[str] = None
    target_files: List[str] = field(default_factory=list)
    config_overrides: Dict[str, Any] = field(default_factory=dict)
    validation_commands: List[str] = field(default_factory=list)
    success_criteria: List[str] = field(default_factory=list)
    risk_notes: List[str] = field(default_factory=list)
    requires_approval: bool = False

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class StrategyProjectContext:
    """Compact local context passed into the multi-role strategy loop."""

    objective: str
    generated_at: str
    candidate_summary: Dict[str, Any] = field(default_factory=dict)
    recent_strategy_rows: List[Dict[str, Any]] = field(default_factory=list)
    recent_system_rows: List[Dict[str, Any]] = field(default_factory=list)
    available_artifacts: Dict[str, Any] = field(default_factory=dict)
    artifact_summaries: Dict[str, Any] = field(default_factory=dict)
    config_summaries: Dict[str, Any] = field(default_factory=dict)
    memory_context: List[str] = field(default_factory=list)
    repo_capabilities: List[str] = field(default_factory=list)
    constraints: List[str] = field(default_factory=list)
    research_constraints: Dict[str, Any] = field(default_factory=dict)
    source_projects: Dict[str, Any] = field(default_factory=dict)

    @classmethod
    def new(cls, objective: str) -> "StrategyProjectContext":
        return cls(
            objective=objective,
            generated_at=datetime.now().isoformat(timespec="seconds"),
        )

    def to_prompt_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class StrategyIterationPlan:
    """Final artifact of a multi-role strategy iteration planning run."""

    run_id: str
    objective: str
    generated_at: str
    role_reports: List[RoleReport]
    experiment_arms: List[ExperimentArm]
    validation_ladder: List[str]
    decision_gates: List[str]
    synthesis: str
    next_actions: List[str] = field(default_factory=list)
    discussion_decisions: List[ChairDecision] = field(default_factory=list)
    research_constraints: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        payload = asdict(self)
        payload["role_reports"] = [r.to_dict() for r in self.role_reports]
        payload["experiment_arms"] = [a.to_dict() for a in self.experiment_arms]
        payload["discussion_decisions"] = [d.to_dict() for d in self.discussion_decisions]
        return payload

    def to_markdown(self) -> str:
        lines = [
            f"# Agent Strategy Iteration Plan: {self.run_id}",
            "",
            f"- Generated: {self.generated_at}",
            f"- Objective: {self.objective}",
            "",
            "## Synthesis",
            self.synthesis,
            "",
            "## Role Reports",
        ]
        if self.discussion_decisions:
            lines.extend(["", "## Discussion Chair Decisions"])
            for decision in self.discussion_decisions:
                target = ", ".join(decision.next_roles) or decision.next_role or "final"
                lines.extend(
                    [
                        "",
                        f"### Turn {decision.turn_index}: {decision.action} -> {target}",
                        f"- Decision: {decision.decision}",
                        f"- Confidence: {decision.confidence:.2f}",
                        f"- Focus: {decision.focus or 'none'}",
                        f"- Rationale: {decision.rationale or 'none'}",
                    ]
                )
                if decision.final_summary:
                    lines.append(f"- Final summary: {decision.final_summary}")
                if decision.missing_requirements:
                    lines.append(f"- Missing requirements: {', '.join(decision.missing_requirements)}")
                if decision.blocked_reason:
                    lines.append(f"- Blocked reason: {decision.blocked_reason}")
        if self.research_constraints:
            metric_policy = self.research_constraints.get("metric_policy") or {}
            lines.extend(
                [
                    "",
                    "## Research Constraints",
                    f"- Default controls: {', '.join(self.research_constraints.get('default_controls') or []) or 'none'}",
                    f"- Rank metric: {metric_policy.get('rank_metric') or 'none'}",
                    f"- Promotion evidence: {metric_policy.get('promotion_evidence') or 'none'}",
                    "- Known traps:",
                    *[f"  - {item}" for item in self.research_constraints.get("known_traps") or []],
                    "- Required plan fields:",
                    *[f"  - {item}" for item in self.research_constraints.get("required_plan_fields") or []],
                ]
            )
        for report in self.role_reports:
            lines.extend(
                [
                    "",
                    f"### {report.role}",
                    report.thesis,
                    "",
                    "Evidence:",
                    *[f"- {item}" for item in report.evidence],
                    "Proposals:",
                    *[f"- {item}" for item in report.proposals],
                    "Risks:",
                    *[f"- {item}" for item in report.risks],
                    f"Verdict: {report.verdict} | Confidence: {report.confidence:.2f}",
                ]
            )
        lines.extend(["", "## Experiment Arms"])
        for arm in self.experiment_arms:
            lines.extend(
                [
                    "",
                    f"### {arm.arm_id}",
                    f"- Type: {arm.change_type}",
                    f"- Owner role: {arm.owner_role}",
                    f"- Hypothesis: {arm.hypothesis}",
                    f"- Requires approval: {arm.requires_approval}",
                    "- Validation:",
                    *[f"  - `{cmd}`" for cmd in arm.validation_commands],
                    "- Success criteria:",
                    *[f"  - {criterion}" for criterion in arm.success_criteria],
                    "- Risks:",
                    *[f"  - {risk}" for risk in arm.risk_notes],
                ]
            )
        lines.extend(["", "## Validation Ladder", *[f"- {item}" for item in self.validation_ladder]])
        lines.extend(["", "## Decision Gates", *[f"- {item}" for item in self.decision_gates]])
        lines.extend(["", "## Next Actions", *[f"- {item}" for item in self.next_actions]])
        return "\n".join(lines) + "\n"


@dataclass
class StrategyIterationRun:
    """Serializable bundle produced by a strategy iteration planning run."""

    run_id: str
    objective: str
    generated_at: str
    context: StrategyProjectContext
    plan: StrategyIterationPlan
    discussion_mode: str = "sequential"
    discussion_settings: Dict[str, Any] = field(default_factory=dict)
    prompts: Dict[str, str] = field(default_factory=dict)
    role_traces: List[Dict[str, Any]] = field(default_factory=list)
    discussion_trace: List[Dict[str, Any]] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "run_id": self.run_id,
            "objective": self.objective,
            "generated_at": self.generated_at,
            "context": self.context.to_prompt_dict(),
            "plan": self.plan.to_dict(),
            "discussion_mode": self.discussion_mode,
            "discussion_settings": dict(self.discussion_settings),
            "prompts": dict(self.prompts),
            "role_traces": list(self.role_traces),
            "discussion_trace": list(self.discussion_trace),
        }


@dataclass
class CommandProposal:
    """One proposed validation or execution command with approval metadata."""

    command_id: str
    command: str
    purpose: str
    source: str
    risk_tags: List[str] = field(default_factory=list)
    requires_approval: bool = True
    approval_reason: str = ""
    timeout_seconds: int = 120
    command_sha256: str = ""

    def __post_init__(self) -> None:
        if not self.command_sha256:
            self.command_sha256 = sha256(self.command.encode("utf-8")).hexdigest()

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class CommandExecutionResult:
    """Captured result for a command executed by the safe runner."""

    command_id: str
    command: str
    skipped: bool
    returncode: Optional[int] = None
    started_at: Optional[str] = None
    ended_at: Optional[str] = None
    stdout_tail: str = ""
    stderr_tail: str = ""
    skip_reason: str = ""
    approval_reason: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class FeedbackCandidate:
    """Result artifact that can be routed into the feedback evaluator."""

    command_id: str
    result_kind: str
    result_csv: str
    ready: bool
    feedback_command: str = ""
    reason: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class CommandApproval:
    """One explicit approval entry for a command proposal."""

    command_id: str
    command_sha256: str
    approved: bool = False
    approved_by: str = ""
    reason: str = ""
    approved_at: str = ""

    @classmethod
    def from_dict(cls, payload: Dict[str, Any]) -> "CommandApproval":
        return cls(
            command_id=str(payload.get("command_id") or ""),
            command_sha256=str(payload.get("command_sha256") or ""),
            approved=bool(payload.get("approved", False)),
            approved_by=str(payload.get("approved_by") or ""),
            reason=str(payload.get("reason") or ""),
            approved_at=str(payload.get("approved_at") or ""),
        )

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class CommandExecutionPlan:
    """Auditable command plan produced from an agent strategy plan."""

    run_id: str
    generated_at: str
    policy: str
    commands: List[CommandProposal] = field(default_factory=list)
    results: List[CommandExecutionResult] = field(default_factory=list)
    feedback_candidates: List[FeedbackCandidate] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "run_id": self.run_id,
            "generated_at": self.generated_at,
            "policy": self.policy,
            "commands": [item.to_dict() for item in self.commands],
            "results": [item.to_dict() for item in self.results],
            "feedback_candidates": [item.to_dict() for item in self.feedback_candidates],
        }

    def to_markdown(self) -> str:
        lines = [
            f"# Agent Command Plan: {self.run_id}",
            "",
            f"- Generated: {self.generated_at}",
            f"- Policy: {self.policy}",
            "",
            "## Commands",
        ]
        for item in self.commands:
            lines.extend(
                [
                    "",
                    f"### {item.command_id}",
                    f"- Source: {item.source}",
                    f"- Purpose: {item.purpose}",
                    f"- Risk tags: {', '.join(item.risk_tags) or 'none'}",
                    f"- Requires approval: {item.requires_approval}",
                    f"- Approval reason: {item.approval_reason or 'none'}",
                    f"- Timeout seconds: {item.timeout_seconds}",
                    f"- Command SHA256: `{item.command_sha256}`",
                    f"- Command: `{item.command}`",
                ]
            )
        if self.results:
            lines.extend(["", "## Results"])
            for result in self.results:
                status = "skipped" if result.skipped else f"returncode={result.returncode}"
                lines.extend(
                    [
                        "",
                        f"### {result.command_id}",
                        f"- Status: {status}",
                        f"- Skip reason: {result.skip_reason or 'none'}",
                        f"- Approval reason: {result.approval_reason or 'none'}",
                    ]
                )
        if self.feedback_candidates:
            lines.extend(["", "## Feedback Candidates"])
            for candidate in self.feedback_candidates:
                lines.extend(
                    [
                        "",
                        f"### {candidate.command_id}",
                        f"- Kind: {candidate.result_kind}",
                        f"- Ready: {candidate.ready}",
                        f"- Result CSV: `{candidate.result_csv}`",
                        f"- Reason: {candidate.reason or 'none'}",
                        f"- Feedback command: `{candidate.feedback_command}`",
                    ]
                )
        return "\n".join(lines) + "\n"


@dataclass
class AgentTaskProposal:
    """One approved-by-user coding-agent task proposal."""

    task_id: str
    title: str
    prompt: str
    provider: str = "codex"
    mode: str = "readonly"
    source: str = ""
    target_files: List[str] = field(default_factory=list)
    allowed_paths: List[str] = field(default_factory=list)
    requires_approval: bool = True
    approval_reason: str = ""
    timeout_seconds: int = 1800
    prompt_sha256: str = ""

    def __post_init__(self) -> None:
        if not self.prompt_sha256:
            self.prompt_sha256 = sha256(self.prompt.encode("utf-8")).hexdigest()

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class AgentTaskApproval:
    """Explicit approval entry for a coding-agent task."""

    task_id: str
    prompt_sha256: str
    approved: bool = False
    approved_by: str = ""
    reason: str = ""
    approved_at: str = ""

    @classmethod
    def from_dict(cls, payload: Dict[str, Any]) -> "AgentTaskApproval":
        return cls(
            task_id=str(payload.get("task_id") or ""),
            prompt_sha256=str(payload.get("prompt_sha256") or ""),
            approved=bool(payload.get("approved", False)),
            approved_by=str(payload.get("approved_by") or ""),
            reason=str(payload.get("reason") or ""),
            approved_at=str(payload.get("approved_at") or ""),
        )

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class AgentTaskResult:
    """Captured result from a local coding-agent CLI invocation."""

    task_id: str
    provider: str
    mode: str
    skipped: bool
    returncode: Optional[int] = None
    started_at: Optional[str] = None
    ended_at: Optional[str] = None
    worktree_path: str = ""
    result_path: str = ""
    diff_path: str = ""
    stdout_tail: str = ""
    stderr_tail: str = ""
    skip_reason: str = ""
    approval_reason: str = ""
    warning: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class AgentTaskPlan:
    """Auditable plan for delegating bounded work to a local coding-agent CLI."""

    run_id: str
    generated_at: str
    policy: str
    tasks: List[AgentTaskProposal] = field(default_factory=list)
    results: List[AgentTaskResult] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "run_id": self.run_id,
            "generated_at": self.generated_at,
            "policy": self.policy,
            "tasks": [item.to_dict() for item in self.tasks],
            "results": [item.to_dict() for item in self.results],
        }

    def to_markdown(self) -> str:
        lines = [
            f"# Agent Task Plan: {self.run_id}",
            "",
            f"- Generated: {self.generated_at}",
            f"- Policy: {self.policy}",
            "",
            "## Tasks",
        ]
        for item in self.tasks:
            lines.extend(
                [
                    "",
                    f"### {item.task_id}",
                    f"- Title: {item.title}",
                    f"- Provider: {item.provider}",
                    f"- Mode: {item.mode}",
                    f"- Source: {item.source or 'none'}",
                    f"- Target files: {', '.join(item.target_files) or 'none'}",
                    f"- Allowed paths: {', '.join(item.allowed_paths) or 'none'}",
                    f"- Requires approval: {item.requires_approval}",
                    f"- Approval reason: {item.approval_reason or 'none'}",
                    f"- Prompt SHA256: `{item.prompt_sha256}`",
                    "",
                    "Prompt:",
                    "```text",
                    item.prompt,
                    "```",
                ]
            )
        if self.results:
            lines.extend(["", "## Results"])
            for result in self.results:
                status = "skipped" if result.skipped else f"returncode={result.returncode}"
                lines.extend(
                    [
                        "",
                        f"### {result.task_id}",
                        f"- Status: {status}",
                        f"- Mode: {result.mode}",
                        f"- Worktree: `{result.worktree_path or 'none'}`",
                        f"- Result path: `{result.result_path or 'none'}`",
                        f"- Diff path: `{result.diff_path or 'none'}`",
                        f"- Warning: {result.warning or 'none'}",
                        f"- Skip reason: {result.skip_reason or 'none'}",
                    ]
                )
        return "\n".join(lines) + "\n"


@dataclass
class MetricSnapshot:
    """Best-row metric snapshot parsed from a result CSV."""

    source_path: str
    result_kind: str
    rank_metric: str
    row_count: int
    best_row: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class StrategyFeedback:
    """Feedback object generated after an agent plan has measurable outcomes."""

    run_id: str
    generated_at: str
    result: MetricSnapshot
    control: Optional[MetricSnapshot] = None
    deltas: Dict[str, float] = field(default_factory=dict)
    observations: List[str] = field(default_factory=list)
    hypothesis_evaluation: str = "inconclusive"
    decision: str = "hold"
    new_hypothesis: str = ""
    next_ablation: str = ""
    do_not_repeat: List[str] = field(default_factory=list)
    reflection: str = ""

    def to_dict(self) -> Dict[str, Any]:
        payload = asdict(self)
        payload["result"] = self.result.to_dict()
        payload["control"] = self.control.to_dict() if self.control else None
        return payload

    def to_markdown(self) -> str:
        lines = [
            f"# Agent Strategy Feedback: {self.run_id}",
            "",
            f"- Generated: {self.generated_at}",
            f"- Decision: {self.decision}",
            f"- Hypothesis evaluation: {self.hypothesis_evaluation}",
            "",
            "## Result",
            f"- Source: `{self.result.source_path}`",
            f"- Kind: {self.result.result_kind}",
            f"- Rank metric: {self.result.rank_metric}",
            f"- Best row: `{self.result.best_row}`",
        ]
        if self.control:
            lines.extend(
                [
                    "",
                    "## Control",
                    f"- Source: `{self.control.source_path}`",
                    f"- Kind: {self.control.result_kind}",
                    f"- Rank metric: {self.control.rank_metric}",
                    f"- Best row: `{self.control.best_row}`",
                ]
            )
        lines.extend(["", "## Deltas", *[f"- {key}: {value:.6f}" for key, value in self.deltas.items()]])
        lines.extend(["", "## Observations", *[f"- {item}" for item in self.observations]])
        lines.extend(
            [
                "",
                "## Reflection",
                self.reflection,
                "",
                "## Next",
                f"- New hypothesis: {self.new_hypothesis}",
                f"- Next ablation: {self.next_ablation}",
                *[f"- Do not repeat: {item}" for item in self.do_not_repeat],
            ]
        )
        return "\n".join(lines) + "\n"
